# 問題文が存在する場所に応じてモードを選ぶ
mode = "local"

# 問題 ID (必須, 出力 html 名にも使用される)
id = "A"

# 問題文が格納されている場所
# mode が local である場合、Markdown ファイルへのパスを記載する
statement_path = "./tests/A.md"

# サンプルが存在する場所
sample_path = "./tests/"

# 問題制約を書く
[constraints]
    MIN_AB = 1
    MAX_AB = 1_000_000_000
    MIN_T = 1
    MAX_T = 100_000
    ALL_INPUTS_ARE_INTEGERS = "入力は全て整数で与えられる"
