# 問題文が存在する場所に応じてモードを選ぶ
mode = "docs"

# 問題 ID (必須, 出力 html 名にも使用される)
id = "H"

# 問題文が格納されている場所 (必須)
# mode が Docs である場合、Google Docs の Document ID を記載する
# (Document ID とは Docs の URL にある、ランダムのような文字列のことです)
statement_path = "1MoguVNpp2SgJvF0ncPbp_8_x2_GhClMijUjF3U3g8ns"
