# docs mode に関する設定
[docs]
    # credentials.json の場所
    creds_path = "./assets/credentials.json"
    # token.pickle の場所
    token_path = "./assets/token.pickle"

# 出力される HTML のスタイルに関する設定
[style]
    # HTML テンプレート
    template_path = "./assets/template.html"
    # 出力ディレクトリにコピーすべきファイル
    copied_files = [ "./assets/style.css" ]
