# プロジェクト名 (必須: 出力ディレクトリ名になります)
name = "interactive_sample"
# 問題文が存在する場所に応じてモードを選ぶ (必須: "docs" or "local")
mode = "local"

# 出力される HTML のスタイルに関する設定
[style]
    # HTML テンプレート
    template_src = "./sample/assets/template.html"
    # 出力ディレクトリにコピーすべきファイル
    copied_files = [ "./sample/assets/style.css" ]

# 問題ごとに定義を書く
[[problem]]
    # 問題 ID (必須: 出力 html 名にも使用される)
    id = "I"
    # 問題文が格納されている場所
    # mode が Docs である場合、Google Docs の Document ID を記載する
    # (Document ID とは Docs の URL にあるランダムっぽい文字列のことです)
    statement_src = "./sample/I/I.md"
    # 問題制約を書く
    [problem.constraints]
        MIN_N = 1
        MAX_N = 10000
    # 入出力例
    [[problem.samples]]
        id = "sample_00"
        # type は "default" なら省略可能
        type = "interactive"
        interactive_path = "./sample/I/00_sample_00.md"
