name: format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        pip3 install .[dev]

    - name: Run tests
      run: |
        ss-manager -h
        flake8 --max-line-length=88 statements_manager/ setup.py
        black --check --diff statements_manager/ setup.py
        mypy --ignore-missing-imports statements_manager/ setup.py
