name: format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python3 statements_manager.py -h
        flake8 --max-line-length=88 statements_manager.py src
        black --check --diff statements_manager.py src
        mypy --ignore-missing-imports statements_manager.py src

